/*
 *  DEPARTMENTS 테이블과 LOCATIONS 테이블을 사용하여 각 부서가 어느 지역에
 *  위치하는지 알아보세요.
 */

SELECT D.DEPARTMENT_NAME
     , D.MANAGER_ID
     , L.LOCATION_ID
     , L.STREET_ADDRESS
     , L.CITY
     , L.STATE_PROVINCE
  FROM DEPARTMENTS D
  JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID;

/*
 * 지역별로 몇 개의 부서가 배치되었는지 알아내시오.
 */

SELECT L.CITY AS "지역"
     , COUNT(*) AS "부서 갯수"
  FROM DEPARTMENTS D
  JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
 GROUP BY L.CITY;

/*
 *  지역별 사원수가 얼마나 되는지 알아보세요.
 */

SELECT D.LOCATION_ID AS "지역"
     , COUNT(*) AS "사원 수"
  FROM EMPLOYEES E
  JOIN DEPARTMENTS D
    ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
  JOIN LOCATIONS L
    ON D.LOCATION_ID = L.LOCATION_ID
 GROUP BY D.LOCATION_ID;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;