/*
 *  DEPARTMENTS 테이블에 총원(EMP_TOTAL) 컬럼을 추가하여 부서별 인원을 기록할 수 있도록 수정한다.
 */
ALTER TABLE DEPARTMENTS ADD EMP_TOTAL NUMBER;

/*  사원 추가(PROC_ADD_EMPLOYEE) 프로시져를 생성하여 사원을 추가할 때 다음의 기능이 동작하도록 한다.
 *      - EMPLOYEES 테이블에 사원을 추가할 수 있는 최소한의 정보를 이용하여 프로시져가 동작하게 한다.
 *          - INPUT : EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, DEPARMENT_ID
 *      - 추가된 사원의 부서에 맞추어 DEPARTMENTS 테이블의 EMP_TOTAL 컬럼의 총원을 증가시키도록 한다.
 */

SELECT * FROM EMPLOYEES;
SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMPLOYEES';
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'EMPLOYEES';
SELECT * FROM DEPARTMENTS;

CREATE OR REPLACE PROCEDURE PROC_ADD_EMPLOYEE(
      EMP_ID IN NUMBER
    , L_N IN VARCHAR2
    , EMA IN VARCHAR2
    , H_D IN DATE
    , J_I IN VARCHAR2
    , D_I IN NUMBER
)
IS
    CNT NUMBER;
BEGIN
    CNT := 0;

    INSERT INTO EMPLOYEES(EMPLOYEE_ID, LAST_NAME, EMAIL, HIRE_DATE, JOB_ID, DEPARTMENT_ID)
    VALUES (EMP_ID, L_N, EMA, H_D, J_I, D_I);

    SELECT COUNT(*)
    INTO CNT
    FROM EMPLOYEES
    WHERE EMPLOYEES.DEPARTMENT_ID = D_I
    GROUP BY DEPARTMENT_ID;

    CNT := CNT + 1;

    UPDATE DEPARTMENTS
       SET EMP_TOTAL = CNT
     WHERE DEPARTMENT_ID = D_I;
END;

SELECT * FROM USER_ERRORS;

BEGIN
    PROC_ADD_EMPLOYEE(208, 'JW', 'TEST', SYSDATE, 'IT_PROG', 70);
END;


SELECT * FROM USER_ERRORS;

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
/*
 *  사원 수정(PROC_MOD_EMPLOYEE) 프로시져와 사원 삭제(PROC_DEL_EMPLOYEE) 프로시져를 생성하여 다음의 기능이 동작하도록 한다.
 *      - EMPLOYEES 테이블의 사원정보를 수정/삭제 할 수 있는 최소한의 정보를 이용하여 프로시져가 동작하게 한다.
 *      - 사원의 정보를 수정할 때는 급여, 직무, 부서만 수정할 수 있게 한다.
 *      - 수정/삭제된 사원의 부서에 맞추어 DEPARTMENTS 테이블의 EMP_TOTAL 컬럼의 총원을 증가 혹은 감소시키도록 한다.
 *
 *  TRIGGER 로도 생성하여 만들어 본다.
 *  TRIGGER 로 생성하고 테스트 할 떄에는 직접 INSERT, UPDATE, DELETE 쿼리문을 만들어 실행해야 합니다.
 */

SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'EMPLOYEES';

CREATE OR REPLACE PROCEDURE PROC_MOD_EMPLOYEE(
      EMP_ID IN NUMBER
    , SAL IN NUMBER
    , JID IN VARCHAR2
    , DEPT_ID IN VARCHAR2
)
IS
    CNT NUMBER;
BEGIN
    UPDATE EMPLOYEES
       SET SALARY = SAL
         , JOB_ID = JID
         , DEPARTMENT_ID = DEPT_ID
    WHERE EMPLOYEE_ID = EMP_ID;
END;

SELECT * FROM USER_ERRORS;

BEGIN
    PROC_MOD_EMPLOYEE(208, 90000, 'IT_PROG', 80);
END;

SELECT * FROM EMPLOYEES;


CREATE OR REPLACE PROCEDURE PROC_DEL_EMPLOYEE(
        EMP_ID IN NUMBER
      , D_I IN NUMBER
)
IS
    CNT NUMBER;
BEGIN
    DELETE FROM EMPLOYEES WHERE EMPLOYEE_ID = EMP_ID;

    SELECT COUNT(*)
      INTO CNT
      FROM EMPLOYEES
     WHERE DEPARTMENT_ID = D_I
     GROUP BY DEPARTMENT_ID;

    UPDATE DEPARTMENTS
       SET EMP_TOTAL = CNT
     WHERE DEPARTMENT_ID = D_I;
END;

SELECT * FROM USER_ERRORS;

BEGIN
    PROC_DEL_EMPLOYEE(208, 80);
END;









