/*
 *  부서별 평균, 최대, 최소 급여를 집계한 DEPT_SALARY_STATICS 테이블을 만들어
 *  데이터를 추가하시오
 */

CREATE TABLE DEPT_SALARY_STATICS
AS
SELECT DEPARTMENT_ID
     , AVG(SALARY) AS "부서별 급여 평균"
     , MAX(SALARY) AS "부서별 급여 최대"
     , MIN(SALARY) AS "부서별 급여 최소"
  FROM EMPLOYEES
GROUP BY DEPARTMENT_ID;

SELECT * FROM DEPT_SALARY_STATICS;

DROP TABLE DEPT_SALARY_STATICS;

/*
 *  직급별 평균, 최대, 최소 급여를 집계한 JOB_SALARY_STATICS 테이블을 만들어
 *  데이터를 추가하시오.
 */


CREATE TABLE JOB_SALARY_STATICS
AS
SELECT JOB_ID
, AVG(SALARY) AS 평균
, MAX(SALARY) AS 최대
, MIN(SALARY) AS 최소
FROM EMPLOYEES
GROUP BY JOB_ID;

DROP TABLE JOB_SALARY_STATICS;

SELECT * FROM JOB_SALARY_STATICS;
/*
 *  직급 ID에 'MGR'이 접두사로 붙은 JOB_SALARY_STATICS에 평균, 최대, 최소 급여를 +500 하세요
 */

UPDATE JOB_SALARY_STATICS
SET 평균 = 평균 + 500, 최대 = 최대 + 500, 최소 = 최소 +500
    WHERE JOB_ID LIKE '%MGR%';

SELECT * FROM JOB_SALARY_STATICS WHERE JOB_ID LIKE '%MGR%';


/*
 *  년도별 입사 인원을 파악하기 위한 HIRE_FOR_YEAR 테이블을 만들어 데이터를 추가하시오.
 *  (인원 파악이 주 목적이기 때문에 년도와 인원수만 저장할 수 있으면 됨)
 */

CREATE TABLE HIRE_FOR_YEAR
AS
    SELECT SUBSTR(TO_CHAR(HIRE_DATE, 'YYYYMMDD'), 0, 4) AS 입사년도
         , COUNT(*) AS 인원
    FROM EMPLOYEES
    GROUP BY SUBSTR(TO_CHAR(HIRE_DATE, 'YYYYMMDD'), 0, 4);

DROP TABLE HIRE_FOR_YEAR;

SELECT * FROM HIRE_FOR_YEAR;
/*
 * 부서별 / 직급별 평균, 최대, 최소 급여를 저장한 테이블에 COMMISSION_PCT까지 반영한
 * 데이터가 저장될 수 있도록 기존 정보를 수정하시오.
 */

ALTER TABLE DEPT_SALARY_STATICS ADD COMMISSION_PCT NUMBER;
/*
INSERT INTO DEPT_SALARY_STATICS(
    SELECT DEPARTMENT_ID,
           COMMISSION_PCT
    FROM EMPLOYEES
    GROUP BY EMPLOYEES.DEPARTMENT_ID
);*/

UPDATE DEPT_SALARY_STATICS
    SET COMMISSION_PCT = (SELECT COMMISSION_PCT FROM EMPLOYEES GROUP BY DEPARTMENT_ID);


SELECT * FROM EMPLOYEES;
